<?php

/**
 * Implements hook_preprocess_page(). Used to add css and js library to content import page.
 * 
 */
function contentimport_preprocess_page(&$variables) {
	$variables['page']['#cache']['contexts'][] = 'route';
	$urlRoute = \Drupal::routeMatch()->getRouteName();    
	if (($urlRoute == 'contentimport.admin_settings')) {
		$variables['#attached']['library'][] = 'contentimport/common-styling';
	}
}
